import { expect, type Page } from '@playwright/test'

export async function checkCrossTeamCallups(page: Page, projectName: string) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await page.locator('.season-card').first().getByRole('button', { name: 'Competiciones (2)' }).click()
  const competitions = page.getByRole('dialog', { name: 'Competiciones' })
  await competitions.getByRole('button', { name: 'Editar Liga Aragonesa' }).click()
  await competitions.getByRole('checkbox', { name: 'Máximo 7 jugadoras repetidas de la última acta del otro equipo' }).check()
  expect(await competitions.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: `/tmp/unizar-cross-team-competition-${projectName}.png`, fullPage: true })
  await competitions.getByRole('button', { name: 'Guardar cambios' }).click()
  await competitions.getByRole('button', { name: 'Editar Liga Aragonesa' }).click()
  await expect(competitions.getByRole('checkbox', { name: /Máximo 7/ })).toBeChecked()
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Partidos' }).click()
  const open = page.getByRole('button', { name: 'Preparar convocatoria con límite de siete' })
  await open.click()
  let editor = page.getByRole('dialog')
  await expect(editor.getByRole('region', { name: 'Límite de jugadoras repetidas' })).toContainText('8/7')
  await editor.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).check()
  await expect(editor.getByRole('button', { name: 'Guardar alineación' })).toBeDisabled()
  await editor.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).uncheck()
  await editor.getByRole('button', { name: 'Guardar alineación' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await open.click()
  editor = page.getByRole('dialog')
  await editor.getByRole('button', { name: 'Quitar a Helena Mora' }).click()
  await expect(editor.getByRole('region', { name: 'Límite de jugadoras repetidas' })).toContainText('7/7')
  await editor.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).check()
  await expect(editor.getByRole('button', { name: 'Guardar alineación' })).toBeEnabled()
  await editor.getByRole('button', { name: 'Guardar alineación' }).click()
  await page.getByRole('button', { name: 'Publicar igualmente' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await open.click()
  await page.getByRole('button', { name: 'Desbloquear para editar' }).click()
  await page.getByRole('button', { name: 'Sí, desbloquear' }).click()
  await page.getByRole('checkbox', { name: 'Acta anterior del A confirmada' }).uncheck()
  await open.click()
  editor = page.getByRole('dialog')
  await expect(editor.getByRole('region', { name: 'Límite de jugadoras repetidas' })).toContainText('Acta pendiente de confirmar')
  await editor.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).check()
  await expect(editor.getByRole('button', { name: 'Guardar alineación' })).toBeDisabled()
  await editor.getByRole('region', { name: 'Límite de jugadoras repetidas' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: `/tmp/unizar-cross-team-callups-${projectName}.png`, fullPage: true })
  expect(await editor.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
}
