import { expect, test } from '@playwright/test'

test('owner creates and reopens a survey draft on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Encuestas' }).click()
  await page.getByRole('button', { name: 'Crear encuesta' }).click()

  const editor = page.getByRole('dialog', { name: 'Crear encuesta' })
  await expect(editor.getByLabel('Visibilidad')).toHaveValue('Privada')
  await editor.getByLabel('Título').fill('Encuesta E2E de recuperación')
  await editor.getByLabel('Descripción / finalidad').fill('Explica cómo ha ido la recuperación para adaptar la próxima semana.')
  await editor.getByRole('textbox', { name: 'Pregunta 1', exact: true }).fill('¿Cómo valoras la recuperación?')
  await editor.getByRole('textbox', { name: 'Opción 1 de pregunta 1', exact: true }).fill('Buena')
  await editor.getByRole('textbox', { name: 'Opción 2 de pregunta 1', exact: true }).fill('Mejorable')
  await editor.getByRole('button', { name: '+ Añadir opción' }).click()
  await editor.getByRole('textbox', { name: 'Opción 3 de pregunta 1', exact: true }).fill('Necesito seguimiento')
  await editor.getByRole('button', { name: '+ Añadir pregunta' }).click()
  await expect(editor.getByLabel('Tipo').nth(1)).toHaveValue('single')
  await editor.getByRole('textbox', { name: 'Pregunta 2', exact: true }).fill('¿Qué cambiarías esta semana?')
  await editor.getByRole('button', { name: 'Guardar borrador' }).click()

  const surveyCard = page.getByRole('button', { name: /Encuesta E2E de recuperación/ })
  await expect(surveyCard).toContainText('Privada')
  await expect(surveyCard).toContainText('Borrador')
  await expect(surveyCard).toContainText('Explica cómo ha ido la recuperación para adaptar la próxima semana.')
  await surveyCard.click()
  const results = page.getByRole('dialog', { name: /Encuesta \d+ · Encuesta E2E de recuperación/ })
  await expect(results.getByText('Explica cómo ha ido la recuperación para adaptar la próxima semana.')).toBeVisible()
  await expect(results.getByRole('button', { name: 'Editar encuesta' })).toBeVisible()
})

test('coach cannot create a private survey', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('coach')
  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Encuestas' }).click()
  await page.getByRole('button', { name: 'Crear encuesta' }).click()

  const editor = page.getByRole('dialog', { name: 'Crear encuesta' })
  await expect(editor.getByLabel('Visibilidad')).toHaveValue('Gestión')
  await expect(editor.getByRole('option', { name: 'Privada' })).toHaveCount(0)
})

test('owner saves a holiday and sees it in the calendar', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  const seasonCard = page.locator('.season-card').filter({ hasText: 'Temporada 2026/2027' })
  await seasonCard.getByRole('button', { name: /Festivos/ }).click()

  const dialog = page.getByRole('dialog', { name: /Festivos · Temporada 2026\/2027/ })
  for (let month = 0; month < 8; month += 1) {
    await dialog.getByRole('button', { name: 'Mes siguiente' }).click()
  }
  await expect(dialog.getByRole('heading', { name: 'septiembre de 2026' })).toBeVisible()
  const ninth = dialog.getByRole('button', { name: '9', exact: true })
  await ninth.click()
  await expect(ninth).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByRole('button', { name: 'Guardar festivos' }).click()
  await expect(page.getByText('Festivos guardados en la demo.')).toBeVisible()
  await expect(seasonCard.getByRole('button', { name: 'Festivos (4)' })).toBeVisible()

  await page.getByRole('button', { name: 'Calendario' }).click()
  const calendar = page.getByRole('region', { name: 'Calendario de planificación' })
  const holiday = calendar.getByRole('button', { name: /^9 de septiembre:/ })
  await expect(holiday).toHaveClass(/holiday/)
  await holiday.click()
  await expect(page.getByText('Sin entrenamiento de campo programado')).toBeVisible()
})

test('published match graphic fits inside the mobile detail', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await page.getByRole('button', { name: 'Ver detalle de Unizar Fem. vs Ingenieros Industriales' }).click()
  const dialog = page.getByRole('dialog', { name: 'Unizar Fem. vs Ingenieros Industriales' })
  await expect(dialog.getByRole('img', { name: 'Imagen de la convocatoria' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Ver lista' }).click()
  await expect(dialog.getByRole('heading', { name: 'Titulares' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Ver imagen' }).click()
  await expect(dialog.getByRole('img', { name: 'Imagen de la convocatoria' })).toBeVisible()
  const widths = await dialog.evaluate((element) => ({ content: element.scrollWidth, visible: element.clientWidth }))
  expect(widths.content).toBeLessThanOrEqual(widths.visible + 1)
  await dialog.getByRole('button', { name: 'Ampliar imagen de la convocatoria' }).click()
  const zoomDialog = page.getByRole('dialog', { name: 'Vista gráfica' })
  const preview = zoomDialog.locator('.lineup-graphic-preview')
  const box = await preview.boundingBox()
  expect(box).not.toBeNull()
  const centerX = box!.x + box!.width / 2
  const centerY = box!.y + 90
  const client = await page.context().newCDPSession(page)
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: centerX - 40, y: centerY, id: 1 }, { x: centerX + 40, y: centerY, id: 2 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: centerX - 80, y: centerY, id: 1 }, { x: centerX + 80, y: centerY, id: 2 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(zoomDialog.getByRole('button', { name: 'Restablecer zoom' })).toHaveText('200 %')
  await expect(zoomDialog.getByRole('img', { name: 'Imagen de la convocatoria' })).toHaveCSS('width', `${Math.round(box!.width * 2)}px`)
})

test('owner can inspect the graphic lineup on mobile without horizontal overflow', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Ver ejemplo gráfico XV' }).click()
  const dialog = page.getByRole('dialog', { name: 'Vista gráfica' })
  await expect(dialog.getByRole('img', { name: 'Imagen de la convocatoria' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Descargar PNG' })).toBeEnabled()
  const widths = await dialog.evaluate((element) => ({ content: element.scrollWidth, visible: element.clientWidth }))
  expect(widths.content).toBeLessThanOrEqual(widths.visible + 1)
})

test('owner manages season teams and assignments in the local demo', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await page.locator('.season-card').first().getByRole('button', { name: 'Gestionar equipos' }).click()

  const dialog = page.getByRole('dialog', { name: 'Equipos' })
  const defaultTeam = dialog.getByRole('region', { name: /Unizar Femenino, \d+ jugadoras/ })
  await expect(defaultTeam.getByText('Marta Sánchez')).toBeVisible()
  await expect(defaultTeam.getByLabel('1 jugadora de baja deportiva hoy')).toBeVisible()
  await expect(defaultTeam.locator('.season-team-player').filter({ hasText: 'Sara Jiménez' }).getByRole('img', { name: 'Baja deportiva' })).toBeVisible()
  await page.screenshot({ path: '/tmp/unizar-season-injuries-mobile.png', fullPage: true })
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  const developmentTeam = dialog.getByRole('region', { name: 'Equipo de desarrollo, 0 jugadoras' })
  await expect(developmentTeam).toBeVisible()
  const firstBox = await defaultTeam.boundingBox()
  const secondBox = await developmentTeam.boundingBox()
  expect(firstBox).not.toBeNull()
  expect(secondBox).not.toBeNull()
  expect(secondBox!.y).toBeGreaterThan(firstBox!.y + firstBox!.height - 1)
  await dialog.getByRole('searchbox', { name: 'Buscar jugadora' }).fill('Marta')
  await expect(defaultTeam.getByLabel('1 jugadora de baja deportiva hoy')).toBeVisible()
  await expect(dialog.getByRole('region', { name: 'Equipo de desarrollo, 0 jugadoras' })).toHaveCount(0)
  await dialog.getByRole('searchbox', { name: 'Buscar jugadora' }).clear()

  await dialog.getByRole('button', { name: 'Nuevo equipo' }).click()
  await dialog.getByLabel('Nombre').fill('Unizar Mixto')
  await dialog.getByLabel('Grupo mixto').check()
  await dialog.getByRole('button', { name: 'Guardar equipo' }).click()

  const mixedTeam = dialog.getByRole('region', { name: 'Unizar Mixto, 0 jugadoras' })
  await expect(mixedTeam).toContainText('Grupo mixto · Activo')
  await defaultTeam.getByRole('button', { name: 'Mover a Marta Sánchez a otro equipo' }).click()
  await expect(dialog.getByText('Equipo actual: Unizar Femenino')).toBeVisible()
  await dialog.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Unizar Mixto/ }).click()
  await expect(dialog.getByRole('region', { name: 'Unizar Mixto, 1 jugadora' }).getByText('Marta Sánchez')).toBeVisible()

  await dialog.getByRole('button', { name: 'Editar entrenadores de Unizar Mixto' }).click()
  await dialog.getByRole('checkbox', { name: 'Andrea López' }).check()
  await dialog.getByRole('checkbox', { name: 'Lucía Martín' }).check()
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(dialog.getByRole('region', { name: 'Unizar Mixto, 1 jugadora' })).toContainText('Andrea López')
  await expect(dialog.getByRole('region', { name: 'Unizar Mixto, 1 jugadora' })).toContainText('Lucía Martín')

  await dialog.getByRole('button', { name: 'Editar equipo Unizar Mixto' }).click()
  await dialog.getByLabel('Nombre').fill('Unizar Mixto A')
  await dialog.getByRole('button', { name: 'Guardar equipo' }).click()
  await expect(dialog.getByRole('region', { name: 'Unizar Mixto A, 1 jugadora' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Mover a Marta Sánchez a otro equipo' }).click()
  await dialog.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Unizar Femenino/ }).click()
  await defaultTeam.getByRole('button', { name: 'Mover a Sara Jiménez a otro equipo' }).click()
  await dialog.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Unizar Mixto A/ }).click()
  const injuredTeam = dialog.getByRole('region', { name: 'Unizar Mixto A, 1 jugadora' })
  await expect(injuredTeam.getByLabel('1 jugadora de baja deportiva hoy')).toBeVisible()
  await expect(defaultTeam.getByLabel('0 jugadoras de baja deportiva hoy')).toBeVisible()
  await injuredTeam.getByRole('button', { name: 'Mover a Sara Jiménez a otro equipo' }).click()
  await dialog.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Unizar Femenino/ }).click()
  await expect(defaultTeam.getByLabel('1 jugadora de baja deportiva hoy')).toBeVisible()
  await dialog.getByRole('button', { name: 'Editar equipo Unizar Mixto A' }).click()
  page.once('dialog', (confirmation) => confirmation.accept())
  await dialog.getByRole('button', { name: 'Eliminar equipo' }).click()
  await expect(dialog.getByRole('region', { name: /Unizar Mixto A/ })).toHaveCount(0)
})

test('owner creates a season competition and uses it as the default match competition', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  const seasonCard = page.locator('.season-card').filter({ hasText: 'Temporada 2026/2027' })
  await seasonCard.getByRole('button', { name: 'Competiciones (2)' }).click()

  const competitionsDialog = page.getByRole('dialog', { name: 'Competiciones' })
  await expect(competitionsDialog.getByText('Liga Aragonesa')).toBeVisible()
  await expect(competitionsDialog.getByText('Copa Aragón')).toBeVisible()
  await competitionsDialog.getByRole('button', { name: 'Nueva competición' }).click()
  await competitionsDialog.getByLabel('Nombre').fill('Copa Catalana')
  await competitionsDialog.getByRole('radio', { name: 'Azul' }).check()
  await competitionsDialog.getByRole('button', { name: 'Crear competición' }).click()

  const catalana = competitionsDialog.locator('.season-competition-row').filter({ hasText: 'Copa Catalana' })
  await catalana.getByRole('button', { name: 'Hacer predeterminada' }).click()
  await expect(catalana.getByText('Predeterminada')).toBeVisible()
  await competitionsDialog.getByRole('button', { name: 'Cerrar', exact: true }).last().click()

  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: 'Añadir' }).click()
  await page.getByRole('menuitem', { name: 'Nuevo partido' }).click()
  const matchDialog = page.getByRole('dialog', { name: 'Nuevo partido' })
  await expect(matchDialog.getByLabel('Competición').locator('option:checked')).toContainText('Copa Catalana · Predeterminada')
  await matchDialog.getByLabel('Rival', { exact: true }).fill('Rival multiliga E2E')
  await matchDialog.getByLabel('Estado').selectOption('published')
  await matchDialog.getByRole('button', { name: 'Guardar partido' }).click()

  const matchCard = page.locator('.match-card').filter({ hasText: 'Rival multiliga E2E' })
  await expect(matchCard.getByText('Copa Catalana')).toBeVisible()
  await expect(matchCard).toHaveCSS('border-left-color', 'rgb(57, 123, 159)')
})

test('permission dependencies remain consistent when saving on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Permisos' }).click()

  await expect(page.getByRole('heading', { name: 'Permisos por rol' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Owner · acceso completo' })).toHaveAttribute('aria-disabled', 'true')
  const viewTasks = page.getByRole('checkbox', { name: 'Ver tareas del equipo' })
  const editTasks = page.getByRole('checkbox', { name: 'Editar tareas' })
  await expect(viewTasks).toBeChecked()
  await viewTasks.uncheck()
  await expect(editTasks).not.toBeChecked()
  await expect(editTasks).toBeDisabled()
  await page.getByRole('button', { name: 'Guardar permisos' }).click()
  await expect(page.getByText('Permisos guardados en la demo.')).toBeVisible()
})
