import { expect, test } from '@playwright/test'

test('records changes and cards manually on mobile', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Gestión' }).click()
  await page.getByRole('menuitem', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Mes anterior' }).click()
  await page.getByRole('button', { name: /: 1 partido/ }).click()
  await page.locator('.selected-planning-week .match-card-summary').filter({ hasText: 'Ingenieros de Soria' }).click()
  await page.getByRole('button', { name: 'Registrar resultado y minutos' }).click()
  const dialog = page.getByRole('dialog', { name: 'Resultado y minutos' })
  await expect(dialog.getByLabel('Importar acta PDF (opcional)')).toBeVisible()
  await expect(dialog.getByLabel('Puntos del equipo')).toBeVisible()
  await dialog.getByLabel('Puntos del equipo').fill('12')
  await dialog.getByLabel('Puntos del rival').fill('7')
  await dialog.getByRole('button', { name: 'Añadir evento' }).click()
  await dialog.getByLabel('Tipo de evento 1').selectOption('yellow_card')
  const player = await dialog.getByLabel('Jugadora del evento 1').getByRole('option', { name: /#1 / }).getAttribute('value')
  await dialog.getByLabel('Jugadora del evento 1').selectOption(player!)
  await dialog.getByLabel('Minuto del evento 1').fill('20')
  await expect(dialog.getByLabel('Minuto de regreso del evento 1')).toHaveValue('30')
  await dialog.getByLabel('Minuto de regreso del evento 1').fill('33')
  await expect(dialog.getByText('67 min', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).scrollIntoViewIfNeeded()
  await expect(dialog.getByRole('button', { name: 'Guardar', exact: true })).toBeDisabled()
  await dialog.getByLabel(/Confirmo que el partido/).check()
  await page.screenshot({ path: '/tmp/unizar-match-result-mobile.png', fullPage: true })
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Resultado y minutos guardados en la demo.')).toBeVisible()
})
