import { expect, test } from '@playwright/test'

test('coach edits positions from the lineup without private data or changing a published callup on mobile', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('coach')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: 'Mes siguiente' }).click()
  await page.getByRole('button', { name: /^1 de octubre:/ }).click()
  await page.locator('.selected-day-matches .match-card-summary').click()
  await page.getByRole('button', { name: 'Gestionar convocatoria' }).click()
  const lineup = page.locator('.lineup-dialog')
  await lineup.getByRole('button', { name: 'Datos de perfil de Claudia Pérez' }).click()
  const profile = page.getByRole('dialog', { name: 'Claudia Pérez' })
  await expect(profile.getByText('Email', { exact: true })).toHaveCount(0)
  await expect(profile.getByText('Fecha de nacimiento', { exact: true })).toHaveCount(0)
  await profile.getByRole('button', { name: 'Acciones de Claudia Pérez' }).click()
  await expect(profile.getByRole('button', { name: 'Editar datos' })).toHaveCount(0)
  await profile.getByRole('button', { name: 'Modificar posiciones' }).click()
  const editor = page.getByRole('dialog', { name: 'Modificar posiciones' })
  await editor.getByRole('checkbox', { name: 'Ala', exact: true }).check()
  await editor.getByRole('combobox').selectOption('wing')
  expect(await editor.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: '/tmp/unizar-posiciones-editor-mobile.png', fullPage: true })
  await editor.getByRole('button', { name: 'Guardar', exact: true }).click()
  await profile.getByRole('button', { name: 'Acciones de Claudia Pérez' }).click()
  await profile.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(lineup.getByRole('button', { name: 'Desbloquear para editar' })).toBeVisible()
  await expect(lineup.getByLabel('Distribución por posición principal')).toContainText('Línea 2')
  expect(await lineup.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})
