import { expect, type Page } from '@playwright/test'

export async function checkPlayerAbsenceDischarge(page: Page, projectName: string, entry: 'menu' | 'pencil') {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Equipo', exact: true }).click()
  await page.getByText('Jugadoras activas', { exact: true }).click()
  const card = page.getByRole('button', { name: 'Ver datos de Sara Jiménez' })
  await expect(card.getByRole('img', { name: 'Baja deportiva' })).toBeVisible()
  await card.click()
  const profile = page.getByRole('dialog', { name: 'Sara Jiménez', exact: true })
  const history = profile.getByRole('region', { name: 'Bajas deportivas' })
  const dates = await history.locator('.team-member-absence-dates > span').innerText()
  if (entry === 'menu') {
    const menuToggle = profile.getByRole('button', { name: 'Acciones de Sara Jiménez' })
    await menuToggle.click()
    const discharge = profile.getByRole('button', { name: 'Alta deportiva', exact: true })
    await expect(discharge).toBeVisible()
    await expect(profile.getByRole('button', { name: 'Baja deportiva', exact: true })).toHaveCount(0)
    expect(await profile.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: `/tmp/unizar-alta-deportiva-menu-${projectName}.png`, fullPage: true })
    page.once('dialog', (dialog) => dialog.dismiss())
    await discharge.click()
    await expect(profile.getByRole('img', { name: 'Baja deportiva' })).toBeVisible()
    await menuToggle.click()
    page.once('dialog', (dialog) => dialog.accept())
    await discharge.click()
  } else {
    await profile.getByRole('button', { name: 'Editar baja deportiva vigente' }).click()
    const editor = page.getByRole('dialog', { name: 'Baja deportiva de Sara Jiménez' })
    const discharge = editor.getByRole('button', { name: 'Dar de alta hoy' })
    await expect(discharge).toBeVisible()
    await expect(editor.getByLabel('Inicio')).toBeDisabled()
    await expect(editor.getByRole('button', { name: 'Guardar cambios' })).toBeVisible()
    expect(await editor.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: `/tmp/unizar-alta-deportiva-${projectName}.png`, fullPage: true })

    page.once('dialog', (dialog) => dialog.dismiss())
    await discharge.click()
    await expect(editor).toBeVisible()
    await editor.getByLabel('Fin previsto').fill('')
    page.once('dialog', (dialog) => dialog.accept())
    await discharge.click()
    await expect(editor).toHaveCount(0)
  }

  await expect(profile).toBeVisible()
  await expect(profile.getByRole('img', { name: 'Baja deportiva' })).toHaveCount(0)
  await expect(history).toContainText('Alta deportiva:')
  await expect(history.locator('.team-member-absence-dates > span')).toHaveText(dates)
  await expect(profile.getByRole('button', { name: 'Editar baja deportiva vigente' })).toHaveCount(0)
  await profile.getByRole('button', { name: 'Acciones de Sara Jiménez' }).click()
  await expect(profile.getByRole('button', { name: 'Baja deportiva', exact: true })).toBeVisible()
  await expect(profile.getByRole('button', { name: 'Alta deportiva', exact: true })).toHaveCount(0)
  await profile.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(card.getByRole('img', { name: 'Baja deportiva' })).toHaveCount(0)
}
