import { expect, type Page } from '@playwright/test'

export async function checkPlayerMatchAccess(page: Page, projectName: string) {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await page.locator('.season-card').first().getByRole('button', { name: 'Gestionar equipos' }).click()
  const teams = page.getByRole('dialog', { name: 'Equipos' })
  await teams.getByRole('button', { name: 'Mover a Marta Sánchez a otro equipo' }).click()
  await teams.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Equipo de desarrollo/ }).click()
  await teams.getByRole('button', { name: 'Cerrar equipos' }).click()

  async function openPlayerDay(day: number) {
    await page.getByLabel('Ver como').selectOption('player')
    await page.getByRole('button', { name: 'Calendario', exact: true }).click()
    await page.getByRole('button', { name: 'Mes siguiente', exact: true }).click()
    await page.getByRole('button', { name: new RegExp(`^${day} de octubre:`) }).click()
  }
  await openPlayerDay(1)
  await page.getByRole('button', { name: /Ver detalle de.*Ingenieros Industriales/ }).click()
  let detail = page.getByRole('dialog')
  await expect(detail.getByRole('heading', { name: 'Convocatoria publicada' })).toBeVisible()
  await detail.getByRole('button', { name: 'Ver lista' }).click()
  await expect(detail.locator('.lineup-roster')).toContainText('Marta Sánchez')
  await detail.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.getByRole('button', { name: /^8 de octubre:/ }).click()
  await page.getByRole('button', { name: 'Asistiré', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cambiar respuesta' })).toBeVisible()

  for (const type of ['none', 'training']) {
    await page.getByLabel('Ver como').selectOption('owner')
    await page.getByRole('button', { name: 'Ajustes' }).click()
    await page.getByRole('menuitem', { name: 'Equipo', exact: true }).click()
    await page.locator('.team-member-group').filter({ hasText: 'Jugadoras activas' }).locator('summary').click()
    await page.getByRole('button', { name: /Ver datos de Marta Sánchez/ }).click()
    const profile = page.getByRole('dialog', { name: 'Marta Sánchez' })
    await profile.getByRole('button', { name: 'Acciones de Marta Sánchez' }).click()
    await profile.getByRole('button', { name: 'Modificar ficha' }).click()
    const license = page.getByRole('dialog', { name: 'Modificar ficha' })
    await license.getByLabel('Tipo de ficha').selectOption(type)
    await license.getByRole('button', { name: 'Guardar', exact: true }).click()
    await page.keyboard.press('Escape')
    await openPlayerDay(8)
    await expect(page.getByText('Partido amistoso de preparación.')).toBeVisible()
    await expect(page.locator('.match-card').getByRole('button', { name: /Asistiré|Rechazar|Cambiar respuesta|Modificar respuesta/ })).toHaveCount(0)
    await page.getByRole('button', { name: /Ver detalle de.*Quebrantahuesos Rugby/ }).click()
    detail = page.getByRole('dialog')
    await expect(detail.getByText(/Para responder disponibilidad necesitas ficha Regional o Nacional/)).toBeVisible()
    await expect(detail.getByRole('button', { name: /Asistiré|Rechazar|Cambiar respuesta|Modificar respuesta/ })).toHaveCount(0)
    await page.screenshot({ path: `/tmp/unizar-match-access-${type}-${projectName}.png`, fullPage: true })
    expect(await detail.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
    await detail.getByRole('button', { name: 'Cerrar', exact: true }).click()
    await page.getByRole('button', { name: /^1 de octubre:/ }).click()
    await page.getByRole('button', { name: /Ver detalle de.*Ingenieros Industriales/ }).click()
    detail = page.getByRole('dialog')
    await expect(detail.getByRole('heading', { name: 'Convocatoria publicada' })).toBeVisible()
    await detail.getByRole('button', { name: 'Ver lista' }).click()
    await expect(detail.locator('.lineup-roster')).toContainText('Marta Sánchez')
    await detail.getByRole('button', { name: 'Cerrar', exact: true }).click()
  }
}
