import { expect, test } from '@playwright/test'

test('owner changes a versatile player principal and sees roster counts update once', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Equipo', exact: true }).click()
  await page.locator('.team-member-group').filter({ hasText: 'Jugadoras activas' }).locator('summary').click()
  await expect(page.getByRole('heading', { name: /Delanteras|Línea|Sin posición/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ver datos de Claudia Pérez' }).click()
  const profile = page.getByRole('dialog', { name: 'Claudia Pérez' })
  await expect(profile.locator('.team-member-detail-grid')).toContainText('Posición principalPilar')
  await profile.getByRole('button', { name: 'Acciones de Claudia Pérez' }).click()
  await profile.getByRole('button', { name: 'Modificar posiciones' }).click()
  const editor = page.getByRole('dialog', { name: 'Modificar posiciones' })
  await editor.getByRole('checkbox', { name: 'Ala', exact: true }).check()
  await editor.getByRole('combobox', { name: 'Posición principal' }).selectOption('wing')
  await editor.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(profile.locator('.team-member-detail-grid')).toContainText('Posición principalAla')
  await expect(profile.locator('.team-member-detail-grid')).toContainText('Pilar, Segunda línea')
  await profile.getByRole('button', { name: 'Acciones de Claudia Pérez' }).click()
  await profile.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await page.locator('.season-card').first().getByRole('button', { name: 'Gestionar equipos' }).click()
  const teams = page.getByRole('dialog', { name: 'Equipos' })
  const roster = teams.getByRole('region', { name: 'Unizar Femenino, 4 jugadoras' })
  await expect(roster.getByRole('heading', { name: 'Delanteras 1' })).toBeVisible()
  await expect(roster.getByRole('heading', { name: 'Línea 2' })).toBeVisible()
  await expect(roster.getByRole('heading', { name: 'Sin posición 1' })).toBeVisible()
  await teams.getByRole('searchbox').fill('Marta')
  await expect(roster.getByRole('heading', { name: 'Línea 2' })).toBeVisible()
  expect(await teams.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: '/tmp/unizar-posiciones-equipos-desktop.png', fullPage: true })
})
