import { expect, test } from '@playwright/test'

test('owner edits the license separately and moves players only from season teams', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  async function openProfile() {
    await page.getByRole('button', { name: 'Ajustes' }).click()
    await page.getByRole('menuitem', { name: 'Equipo', exact: true }).click()
    await page.locator('.team-member-group').filter({ hasText: 'Jugadoras activas' }).locator('summary').click()
    await page.getByRole('button', { name: /Ver datos de Marta Sánchez/ }).click()
  }
  async function editLicense() {
    const profile = page.getByRole('dialog', { name: 'Marta Sánchez' })
    await profile.getByRole('button', { name: 'Acciones de Marta Sánchez' }).click()
    await profile.getByRole('button', { name: 'Modificar ficha' }).click()
    return page.getByRole('dialog', { name: 'Modificar ficha' })
  }
  async function openTeams() {
    await page.getByRole('button', { name: 'Ajustes' }).click()
    await page.getByRole('menuitem', { name: 'Temporadas' }).click()
    await page.locator('.season-card').first().getByRole('button', { name: 'Gestionar equipos' }).click()
    return page.getByRole('dialog', { name: 'Equipos' })
  }
  await openProfile()
  const profile = page.getByRole('dialog', { name: 'Marta Sánchez' })
  const details = profile.locator('.team-member-detail-grid')
  await expect(details).toContainText('Regional')
  await expect(profile.getByLabel('Tipo de ficha')).toHaveCount(0)
  let license = await editLicense()
  await expect(license.getByLabel('Tipo de ficha')).toHaveValue('regional')
  await expect(license.getByLabel('Temporada activa')).toHaveAttribute('readonly')
  await expect(license.getByRole('combobox')).toHaveCount(1)
  await license.getByLabel('Tipo de ficha').selectOption({ label: 'Solo entrenamientos' })
  await license.getByRole('button', { name: 'Cancelar' }).click()
  await expect(details).toContainText('Regional')
  license = await editLicense()
  await license.getByLabel('Tipo de ficha').selectOption({ label: 'Solo entrenamientos' })
  await page.screenshot({ path: `/tmp/unizar-license-editor-${test.info().project.name}.png`, fullPage: true })
  expect(await license.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await license.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(profile).toBeVisible()
  await expect(details).toContainText('Solo entrenamientos')
  await expect(details).toContainText('Sin equipo en la temporada activa')
  await page.screenshot({ path: `/tmp/unizar-player-license-${test.info().project.name}.png`, fullPage: true })
  expect(await profile.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.keyboard.press('Escape')
  let teams = await openTeams()
  const unassigned = teams.locator('.season-team-roster-card.unassigned')
  await expect(unassigned).toContainText('Marta Sánchez')
  await expect(unassigned.getByRole('button', { name: 'Mover a Marta Sánchez a otro equipo' })).toBeDisabled()
  await teams.getByRole('button', { name: 'Cerrar equipos' }).click()
  await page.getByRole('button', { name: 'Asistencia', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Registrar asistencia' }).click()
  await expect(page.getByText('Marta Sánchez', { exact: true })).toBeVisible()

  await openProfile()
  license = await editLicense()
  await license.getByLabel('Tipo de ficha').selectOption('regional')
  await license.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(details).toContainText('Sin equipo en la temporada activa')
  await page.keyboard.press('Escape')
  teams = await openTeams()
  await teams.getByRole('button', { name: 'Mover a Marta Sánchez a otro equipo' }).click()
  await teams.getByRole('group', { name: 'Equipo de destino' }).getByRole('button', { name: /Equipo de desarrollo/ }).click()
  await expect(teams.locator('.season-team-roster-card').filter({ hasText: 'Equipo de desarrollo' })).toContainText('Marta Sánchez')
  await teams.getByRole('button', { name: 'Cerrar equipos' }).click()
  await openProfile()
  await expect(details).toContainText('Equipo de desarrollo')
  license = await editLicense()
  await license.getByLabel('Tipo de ficha').selectOption('national')
  await license.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(details).toContainText('Nacional')
  await expect(details).toContainText('Equipo de desarrollo')
})
