import { expect, test } from '@playwright/test'

test('owner plans and reviews task results on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await expect(page.getByRole('region', { name: 'Calendario de planificación' })).toBeVisible()
  await page.getByRole('button', { name: 'Añadir' }).click()
  await page.getByRole('menuitem', { name: 'Nueva tarea' }).click()
  const createDialog = page.getByRole('dialog', { name: 'Crear tarea' })
  await expect(createDialog).toBeVisible()
  await expect(createDialog.getByRole('option', { name: 'Vídeo' })).toHaveCount(1)
  await expect(createDialog.getByRole('option', { name: 'Táctico' })).toHaveCount(0)
  await expect(createDialog.getByRole('option', { name: 'Técnico' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Cerrar' }).click()
  const results = page.getByRole('button', { name: 'Ver resultados' }).first()
  if (await results.isVisible()) {
    await results.click()
    await expect(page.getByRole('dialog')).toContainText('Fatiga media del equipo')
  }
})

test('owner can open demo training plans and find the PDF action', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Entrenamientos' }).click()

  await expect(page.getByText('Modo de muestra local.')).toBeVisible()
  await page.getByRole('button', { name: /Ver entrenamiento/ }).first().click()
  await expect(page.getByText('VISTA DEL ENTRENAMIENTO')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Guardar PDF' })).toBeVisible()

  await page.emulateMedia({ media: 'print' })
  const pdf = await page.pdf({ format: 'A4', printBackground: true })
  const pageCount = pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)?.length ?? 0
  expect(pageCount).toBeGreaterThan(1)
})

test('staff home shows team progress and exposes the linked video task', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('PANEL DEL EQUIPO')).toBeVisible()
  await expect(page.getByText('Jugadoras activas').locator('..')).toContainText('4/4')
  await expect(page.getByText('Progreso del equipo').locator('..')).toContainText('8/12')

  const videoTask = page.locator('.task-card').filter({ hasText: 'Ver partido · Nueva Zelanda contra Australia' })
  const videoLink = videoTask.getByRole('link', { name: 'https://www.youtube.com/watch?v=PW46tR7Ka9Y' })
  await expect(videoLink).toHaveAttribute('href', 'https://www.youtube.com/watch?v=PW46tR7Ka9Y')
  await expect(videoLink).toHaveAttribute('target', '_blank')
})

test('daily attendance groups and task metrics stay compact on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Asistencia' }).click()
  await page.getByRole('menuitem', { name: 'Resumen' }).click()

  const present = page.getByRole('region', { name: /Asistieron: \d+ jugadoras/ })
  const absent = page.getByRole('region', { name: /No asistieron: \d+ jugadoras/ })
  await expect(present.locator('.statistics-player-group-heading')).toHaveCSS('background-color', 'rgb(218, 240, 226)')
  await expect(absent.locator('.statistics-player-group-heading')).toHaveCSS('background-color', 'rgb(255, 240, 237)')

  const metricBox = await present.locator('.statistics-player-metrics > div').first().boundingBox()
  expect(metricBox?.height).toBeLessThan(45)
})

test('owner publishes a dated announcement and a player opens it from home', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: 'Añadir' }).click()
  await page.getByRole('menuitem', { name: 'Nuevo aviso' }).click()
  const dialog = page.getByRole('dialog', { name: 'Crear aviso' })
  await dialog.getByLabel('Título').fill('Reunión rápida del equipo')
  await expect(dialog.getByRole('group', { name: 'Temporada activa' })).toContainText('Temporada 2026')
  await dialog.getByLabel('Descripción').fill('Nos reuniremos al terminar el entrenamiento.')
  await dialog.getByRole('button', { name: 'Crear aviso' }).click()
  await expect(page.getByText('Reunión rápida del equipo')).toBeVisible()

  await page.getByLabel('Ver como').selectOption('player')
  await page.getByText('Para tener en cuenta').click()
  await page.getByRole('button', { name: /Reunión rápida del equipo/ }).click()
  await expect(page.getByRole('dialog', { name: 'Reunión rápida del equipo' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Calendario de planificación' })).toBeVisible()
})

test('player fatigue options remain horizontal on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: 'Completar' }).first().click()
  const box = await page.locator('.fatigue-options').boundingBox()
  expect(box?.width).toBeGreaterThan(250)
  expect(box?.height).toBeLessThan(100)
  await page.locator('.fatigue-options label').last().click()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)
})

test('player opens her profile data and sees the private photo control', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Abrir menú de usuario' }).click()
  await page.getByRole('menuitem', { name: 'Editar mis datos' }).click()

  const dialog = page.getByRole('dialog', { name: 'Datos de perfil' })
  await expect(dialog.getByLabel('Email de Google')).toHaveValue('player@demo.local')
  await expect(dialog.getByText('Fotografía de perfil')).toBeVisible()
  await expect(dialog.getByLabel('Seleccionar fotografía')).toBeAttached()
  await expect(dialog.getByRole('button', { name: 'Guardar datos' })).toBeDisabled()
})

test('match availability and lineup flows work on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /1 cumpleaños/ }).click()
  await expect(page.getByText('Cumpleaños del día').locator('..')).toContainText(/Claudia Pérez cumple \d+ años/)
  await page.getByRole('button', { name: /1 partido/ }).nth(1).click()
  await page.locator('.availability-summary button').first().click()
  await expect(page.getByRole('dialog', { name: /Partido contra/ })).toContainText('En duda')
  await page.getByRole('button', { name: 'Cerrar' }).click()
  await page.getByRole('button', { name: 'Gestionar alineación' }).first().click()
  await expect(page.getByRole('dialog', { name: /Partido contra/ })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).check()
  await page.getByRole('button', { name: 'Guardar alineación' }).click()
  await expect(page.getByRole('dialog', { name: 'Hay titulares sin rellenar' })).toBeVisible()
  await page.getByRole('button', { name: 'Revisar alineación' }).click()
  await page.getByRole('button', { name: 'Cerrar' }).click()

  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await expect(page.locator('.mobile-nav').getByRole('button', { name: 'Tareas' })).toHaveCount(0)
  await expect(page.locator('.mobile-nav').getByRole('button', { name: 'Partidos' })).toHaveCount(0)
  const birthdayDay = page.getByRole('button', { name: /1 cumpleaños/ })
  const birthdayMarkBox = await birthdayDay.locator('.birthday-mark').boundingBox()
  const birthdayDayNumberBox = await birthdayDay.locator(':scope > strong').boundingBox()
  expect(birthdayMarkBox).not.toBeNull()
  expect(birthdayDayNumberBox).not.toBeNull()
  expect(birthdayMarkBox!.x).toBeGreaterThanOrEqual(birthdayDayNumberBox!.x + birthdayDayNumberBox!.width)
  expect(Math.abs(birthdayMarkBox!.y - birthdayDayNumberBox!.y)).toBeLessThanOrEqual(3)
  await birthdayDay.click()
  await expect(page.getByText('Cumpleaños del día').locator('..')).toContainText('Claudia Pérez')
  await page.getByRole('button', { name: /1 partido/ }).nth(1).click()
  await expect(page.getByText('Estás en duda')).toBeVisible()
  await page.getByRole('button', { name: 'Modificar respuesta' }).click()
  await page.getByLabel('Respuesta').selectOption('doubt')
  await page.getByLabel('Comentario opcional').fill('Pendiente de revisión')
  await page.getByRole('button', { name: 'Guardar respuesta' }).click()
  await expect(page.getByText('Disponibilidad mock guardada.')).toBeVisible()
})

test('owner reviews the accumulated callup report on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: 'Resumen de convocatorias' }).click()
  const table = page.getByRole('table')
  await expect(table).toBeVisible()
  await expect(table.getByRole('columnheader', { name: /Oficiales/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Descargar XML' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copiar tabla' })).toBeVisible()
  await page.locator('.callup-player-link').first().click()
  await expect(page.getByRole('dialog')).toContainText('RESUMEN DE TEMPORADA')
  await expect(page.getByRole('dialog')).toContainText('Disponibilidad')
})

test('player sees her seasonal progress from home', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await expect(page.getByText('Asistencia a campo')).toBeVisible()
  await expect(page.getByText('Fatiga media')).toHaveCount(0)
  await page.getByRole('button', { name: /Mi temporada/ }).click()
  const dialog = page.getByRole('dialog', { name: 'Marta Sánchez' })
  await expect(dialog).toContainText('Convocatorias')
  await expect(dialog).toContainText('Partidos de la temporada')
})

test('coach manages sports areas without access to settings', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('coach')
  await expect(page.getByRole('button', { name: 'Asistencia' })).toBeVisible()
  await page.getByRole('button', { name: 'Asistencia' }).click()
  await expect(page.getByRole('menuitem', { name: 'Resumen' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Asistencia' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ajustes' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Calendario' }).click()
  await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /1 cumpleaños/ }).click()
  await expect(page.getByText('Cumpleaños del día').locator('..')).toContainText(/Claudia Pérez cumple \d+ años/)
  await page.getByRole('button', { name: /1 partido/ }).nth(1).click()
  await expect(page.getByRole('button', { name: 'Editar partido' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Competición' }).click()
  await expect(page.getByRole('heading', { name: 'Competición', exact: true })).toBeVisible()
})

test('Dirección can inspect team data but cannot edit it', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('viewer')
  await expect(page.getByRole('button', { name: 'Resumen' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tareas' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Asistencia' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ajustes' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await expect(page.locator('.availability-summary').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Editar partido' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Gestionar alineación' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Asistiré' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Resumen de convocatorias' }).click()
  await expect(page.getByRole('table')).toBeVisible()
})

test('owner manages team and seasons from settings on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Equipo' }).click()
  await expect(page.getByRole('heading', { name: 'Ajustes - Equipo', exact: true })).toBeVisible()
  await expect(page.getByText('Posible duplicado')).toBeVisible()
  const martaCard = page.getByRole('button', { name: 'Ver datos de Marta Sánchez' })
  await expect(martaCard).toContainText('Activa')
  await expect(martaCard.getByRole('checkbox')).toHaveCount(0)
  const emailBox = await martaCard.locator('.person-summary-contact > span').nth(0).boundingBox()
  const phoneBox = await martaCard.locator('.person-summary-contact > span').nth(1).boundingBox()
  const ageBox = await martaCard.locator('.person-summary-contact > span').nth(2).boundingBox()
  const arrowBox = await martaCard.locator(':scope > .icon').boundingBox()
  expect(emailBox?.width).toBeGreaterThan((phoneBox?.width ?? 0) * 1.8)
  expect(Math.abs((phoneBox?.y ?? 0) - (ageBox?.y ?? 0))).toBeLessThan(2)
  expect(arrowBox?.y).toBeLessThan(emailBox?.y ?? 0)
  await page.getByRole('button', { name: 'Buscar personas' }).click()
  await page.getByRole('searchbox', { name: 'Buscar por nombre' }).fill('claudia')
  await expect(page.getByText('Claudia Pérez')).toBeVisible()
  await expect(page.getByText('Marta Sánchez')).toHaveCount(0)
  await page.getByRole('button', { name: 'Cerrar búsqueda' }).click()

  await page.getByRole('button', { name: 'Ver datos de Claudia Pérez' }).click()
  const profileDialog = page.getByRole('dialog', { name: 'Claudia Pérez' })
  await expect(profileDialog.getByAltText('Fotografía de Claudia Pérez')).toBeVisible()
  await expect(profileDialog.locator('.team-member-profile-summary')).toContainText('+34 600 100 104')
  await expect(profileDialog.locator('.team-member-profile-summary')).toContainText('25 años')
  await expect(profileDialog.locator('.team-member-profile-summary')).not.toContainText('claudia@demo.local')
  await profileDialog.getByRole('button', { name: 'Editar datos de Claudia Pérez' }).click()
  await expect(profileDialog.getByText('Fotografía de perfil')).toBeVisible()
  await expect(profileDialog.getByLabel('Email de Google')).toHaveValue('claudia@demo.local')
  await expect(profileDialog.getByLabel('Email de Google')).toHaveAttribute('readonly', '')
  await profileDialog.getByLabel('Nombre y apellidos').fill('Claudia Pérez García')
  await profileDialog.getByLabel('Teléfono').fill('+34 699 123 456')
  await profileDialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByText('Claudia Pérez García', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await expect(page.getByRole('heading', { name: 'Ajustes - Temporadas', exact: true })).toBeVisible()
})

test('player browses the 2025–26 competition on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Competición' }).click()
  await expect(page.getByRole('heading', { name: 'Competición', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Temporada' })).toHaveValue('competition-2025-26')
  await expect(page.getByText('Unizar Femenino').first()).toBeVisible()
  await page.getByRole('button', { name: 'Clasificación' }).click()
  await expect(page.getByRole('table')).toContainText('32')
  await page.getByRole('button', { name: 'Estadísticas' }).click()
  await expect(page.getByText('Ariadna Acirón Matute')).toBeVisible()
})

test('selecting attendance keeps the mobile header and navigation fixed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Asistencia' }).click()
  await page.getByRole('menuitem', { name: 'Registrar asistencia' }).click()
  await expect(page.getByRole('heading', { name: 'Asistencia de hoy' })).toBeVisible()

  const players = page.locator('.attendance-player')
  await players.nth(0).click()
  await players.nth(1).click()

  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)
})

test('owner records an invited player and later links multiple provisional histories', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Asistencia' }).click()
  await page.getByRole('menuitem', { name: 'Registrar asistencia' }).click()
  await expect(page.getByRole('region', { name: 'Invitadas: 5' })).toBeVisible()

  await page.getByRole('button', { name: 'Añadir invitada' }).click()
  const addDialog = page.getByRole('dialog', { name: 'Añadir invitada' })
  await addDialog.getByLabel('Nombre y apellidos').fill('Nueva Jugadora Prueba')
  await addDialog.getByRole('button', { name: 'Añadir invitada' }).click()
  await expect(page.getByRole('region', { name: 'Invitadas: 6' })).toContainText('Nueva Jugadora Prueba')
  await page.getByRole('button', { name: 'Guardar asistencia' }).click()
  await expect(page.getByText('Asistencia mock guardada.')).toBeVisible()

  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Equipo' }).click()
  await page.getByRole('button', { name: 'Ver datos de Nerea Ruiz' }).click()
  const profileDialog = page.getByRole('dialog', { name: 'Nerea Ruiz' })
  await profileDialog.getByRole('checkbox', { name: /Nerea Ruis/ }).check()
  await profileDialog.getByRole('checkbox', { name: /Nueva Jugadora Prueba/ }).check()
  page.once('dialog', (dialog) => dialog.accept())
  await profileDialog.getByRole('button', { name: 'Vincular asistencias' }).click()
  await expect(page.getByText('2 invitadas se han vinculado con Nerea Ruiz.')).toBeVisible()
  await expect(profileDialog).toHaveCount(0)
})

test('scrolling the lineup modal does not move the screen behind it', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendario' }).click()
  await page.getByRole('button', { name: /1 partido/ }).nth(1).click()
  await page.getByRole('button', { name: 'Gestionar alineación' }).first().click()

  const content = page.locator('.content')
  const initialScroll = await content.evaluate((element) => element.scrollTop)
  await expect(content).toHaveCSS('overflow-y', 'hidden')

  const dialog = page.locator('.lineup-dialog')
  await dialog.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await dialog.hover()
  await page.mouse.wheel(0, 1800)

  expect(await content.evaluate((element) => element.scrollTop)).toBe(initialScroll)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)

  await page.getByRole('button', { name: 'Cerrar' }).click()
  await expect(content).toHaveCSS('overflow-y', 'auto')
})
