import { expect, test } from '@playwright/test'

test('owner plans and reviews task results on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Tareas' }).click()
  await expect(page.getByRole('region', { name: 'Calendario de planificación' })).toBeVisible()
  await page.getByRole('button', { name: 'Nueva tarea en esta semana' }).click()
  await expect(page.getByRole('dialog', { name: 'Crear tarea' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar' }).click()
  const results = page.getByRole('button', { name: 'Ver resultados' }).first()
  if (await results.isVisible()) {
    await results.click()
    await expect(page.getByRole('dialog')).toContainText('Fatiga media del equipo')
  }
})

test('owner publishes a dated announcement and a player opens it from home', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Tareas' }).click()
  await page.getByRole('button', { name: 'Nuevo aviso para este día' }).click()
  const dialog = page.getByRole('dialog', { name: 'Crear aviso' })
  await dialog.getByLabel('Título').fill('Reunión rápida del equipo')
  await expect(dialog.getByRole('group', { name: 'Temporada activa' })).toContainText('Temporada 2026')
  await dialog.getByLabel('Descripción').fill('Nos reuniremos al terminar el entrenamiento.')
  await dialog.getByRole('button', { name: 'Crear aviso' }).click()
  await expect(page.getByText('Reunión rápida del equipo')).toBeVisible()

  await page.getByLabel('Ver como').selectOption('player')
  await page.getByText('Para tener en cuenta').click()
  await page.getByRole('button', { name: /Reunión rápida del equipo/ }).click()
  await expect(page.getByRole('dialog', { name: 'Reunión rápida del equipo' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Calendario de planificación' })).toBeVisible()
})

test('player fatigue options remain horizontal on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Tareas' }).click()
  await page.getByRole('button', { name: 'Completar' }).first().click()
  const box = await page.locator('.fatigue-options').boundingBox()
  expect(box?.width).toBeGreaterThan(250)
  expect(box?.height).toBeLessThan(100)
  await page.locator('.fatigue-options label').last().click()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)
})

test('match availability and lineup flows work on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Partidos' }).click()
  await expect(page.getByRole('heading', { name: 'Partidos', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await page.locator('.availability-summary button').first().click()
  await expect(page.getByRole('dialog', { name: /Partido contra/ })).toContainText('En duda')
  await page.getByRole('button', { name: 'Cerrar' }).click()
  await page.getByRole('button', { name: 'Gestionar alineación' }).first().click()
  await expect(page.getByRole('dialog', { name: /Partido contra/ })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Publicar convocatoria para las jugadoras' }).check()
  await page.getByRole('button', { name: 'Guardar alineación' }).click()
  await expect(page.getByRole('dialog', { name: 'Hay titulares sin rellenar' })).toBeVisible()
  await page.getByRole('button', { name: 'Revisar alineación' }).click()
  await page.getByRole('button', { name: 'Cerrar' }).click()

  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Partidos' }).click()
  await expect(page.getByRole('region', { name: 'Calendario de partidos' })).toBeVisible()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await expect(page.getByText('Estás en duda')).toBeVisible()
  await expect(page.getByText('No asistirás')).toBeVisible()
  await page.getByRole('button', { name: 'Modificar respuesta' }).first().click()
  await page.getByLabel('Respuesta').selectOption('doubt')
  await page.getByLabel('Comentario opcional').fill('Pendiente de revisión')
  await page.getByRole('button', { name: 'Guardar respuesta' }).click()
  await expect(page.getByText('Disponibilidad mock guardada.')).toBeVisible()
})

test('owner reviews the accumulated callup report on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Resumen de convocatorias' }).click()
  const table = page.getByRole('table')
  await expect(table).toBeVisible()
  await expect(table.getByRole('columnheader', { name: /Oficiales/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Descargar XML' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copiar tabla' })).toBeVisible()
  await page.locator('.callup-player-link').first().click()
  await expect(page.getByRole('dialog')).toContainText('RESUMEN DE TEMPORADA')
  await expect(page.getByRole('dialog')).toContainText('Disponibilidad')
})

test('player sees her seasonal progress from home', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await expect(page.getByText('Asistencia a campo')).toBeVisible()
  await expect(page.getByText('Fatiga media')).toHaveCount(0)
  await page.getByRole('button', { name: /Mi temporada/ }).click()
  const dialog = page.getByRole('dialog', { name: 'Marta Sánchez' })
  await expect(dialog).toContainText('Convocatorias')
  await expect(dialog).toContainText('Partidos de la temporada')
})

test('coach manages sports areas without access to settings', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('coach')
  await expect(page.getByRole('button', { name: 'Resumen' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Asistencia' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ajustes' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Partidos' }).click()
  await expect(page.getByRole('region', { name: 'Calendario de partidos' })).toBeVisible()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await expect(page.getByRole('button', { name: 'Editar partido' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Competición' }).click()
  await expect(page.getByRole('heading', { name: 'Competición', exact: true })).toBeVisible()
})

test('Dirección can inspect team data but cannot edit it', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('viewer')
  await expect(page.getByRole('button', { name: 'Resumen' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tareas' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Asistencia' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ajustes' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await expect(page.locator('.availability-summary').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Editar partido' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Gestionar alineación' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Asistiré' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Resumen de convocatorias' }).click()
  await expect(page.getByRole('table')).toBeVisible()
})

test('owner manages team and seasons from settings on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await expect(page.getByRole('heading', { name: 'Ajustes', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Equipo', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Temporadas' }).click()
  await expect(page.getByRole('heading', { name: 'Temporadas', exact: true })).toBeVisible()
})

test('player browses the 2025–26 competition on mobile', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Ver como').selectOption('player')
  await page.getByRole('button', { name: 'Competición' }).click()
  await expect(page.getByRole('heading', { name: 'Competición', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Temporada' })).toHaveValue('competition-2025-26')
  await expect(page.getByText('Unizar Femenino').first()).toBeVisible()
  await page.getByRole('button', { name: 'Clasificación' }).click()
  await expect(page.getByRole('table')).toContainText('32')
  await page.getByRole('button', { name: 'Estadísticas' }).click()
  await expect(page.getByText('Ariadna Acirón Matute')).toBeVisible()
})

test('selecting attendance keeps the mobile header and navigation fixed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Asistencia' }).click()
  await expect(page.getByRole('heading', { name: 'Asistencia de hoy' })).toBeVisible()

  const players = page.locator('.attendance-player')
  await players.nth(0).click()
  await players.nth(1).click()

  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)
})

test('scrolling the lineup modal does not move the screen behind it', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Partidos' }).click()
  await page.getByRole('button', { name: 'Vista de lista' }).click()
  await page.getByRole('button', { name: 'Gestionar alineación' }).first().click()

  const content = page.locator('.content')
  const initialScroll = await content.evaluate((element) => element.scrollTop)
  await expect(content).toHaveCSS('overflow-y', 'hidden')

  const dialog = page.locator('.lineup-dialog')
  await dialog.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await dialog.hover()
  await page.mouse.wheel(0, 1800)

  expect(await content.evaluate((element) => element.scrollTop)).toBe(initialScroll)
  const header = await page.locator('.mobile-header').boundingBox()
  const navigation = await page.locator('.mobile-nav').boundingBox()
  expect(header?.y).toBeGreaterThanOrEqual(0)
  expect(header?.y).toBeLessThan(2)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeGreaterThanOrEqual(913)
  expect((navigation?.y ?? 0) + (navigation?.height ?? 0)).toBeLessThanOrEqual(916)

  await page.getByRole('button', { name: 'Cerrar' }).click()
  await expect(content).toHaveCSS('overflow-y', 'auto')
})
