import { expect, type Page } from '@playwright/test'

export async function checkTeamColors(page: Page, projectName: string) {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00+02:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await page.getByRole('menuitem', { name: 'Temporadas' }).click()
  await page.locator('.season-card').first().getByRole('button', { name: 'Gestionar equipos' }).click()
  const teams = page.getByRole('dialog', { name: 'Equipos' })
  await teams.getByRole('button', { name: 'Editar equipo Equipo de desarrollo' }).click()
  await expect(teams.getByRole('radio', { name: 'Verde' })).toBeChecked()
  await teams.getByRole('radio', { name: 'Azul' }).check()
  await page.screenshot({ path: `/tmp/unizar-team-colors-${projectName}.png`, fullPage: true })
  expect(await teams.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await teams.getByRole('button', { name: 'Guardar equipo' }).click()
  await teams.getByRole('button', { name: 'Editar equipo Equipo de desarrollo' }).click()
  await expect(teams.getByRole('radio', { name: 'Azul' })).toBeChecked()
  await teams.getByRole('button', { name: 'Volver a equipos' }).click()
  await teams.getByRole('button', { name: 'Cerrar equipos' }).click()

  await page.getByRole('button', { name: 'Calendario', exact: true }).click()
  await page.getByRole('button', { name: 'Mes siguiente', exact: true }).click()
  await page.getByRole('button', { name: /^8 de octubre:/ }).click()
  const card = page.locator('.match-card').filter({ hasText: 'Quebrantahuesos Rugby' })
  await card.getByRole('button', { name: /Ver detalle/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Editar partido' }).click()
  const form = page.getByRole('dialog')
  await form.getByLabel('Tipo de partido').selectOption('official')
  await form.getByRole('combobox', { name: 'Equipo', exact: true }).selectOption('demo-team-default')
  await form.getByRole('button', { name: 'Guardar partido' }).click()
  await expect(card).toHaveCSS('--match-color', '#7459ae')
  const day = page.getByRole('button', { name: /^8 de octubre:/ })
  await expect(day.locator('.match-day-marks i')).toHaveCSS('background-color', 'rgb(116, 89, 174)')

  await card.getByRole('button', { name: /Ver detalle/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Editar partido' }).click()
  await form.getByRole('combobox', { name: 'Equipo', exact: true }).selectOption('demo-team-development')
  await form.getByRole('button', { name: 'Guardar partido' }).click()
  await expect(card).toHaveCSS('--match-color', '#397b9f')
  await expect(day.locator('.match-day-marks i')).toHaveCSS('background-color', 'rgb(57, 123, 159)')
  await expect(card.locator('.match-competition-label')).toContainText('Liga')
  await page.screenshot({ path: `/tmp/unizar-match-team-color-${projectName}.png`, fullPage: true })
}
